### ISSUE TITLE
Number field takes alphanumerical input

### ISSUE THREAD

**Issue by Rishabh510** [Anantm007/contact-keeper#1]
In the deployed website, the number field can take letters. After trying to add contact, the contact doesn't show up. 
Could be resolved by making number field to accepts numerical digits only.

**Comment by Anantm007** [comment]
Hi,
I have purposedly made the phone as a string because I wanted to incorporate dashes in the number. eg: 111-222-333. The problem was in the Contact model which has now been rectified.

Thanks
